name: igor_app
description: A roleplaying assistant

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.10
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.14.0+8
  firebase_database: ^3.0.9
  firebase_messaging: ^6.0.1
  bloc: ^1.0.1
  json_annotation: ^3.0.0
  gen_lang: ^0.1.2
  http: ^0.12.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  strings: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  fonts:
    - family: FiraSans
      fonts:
        - asset: lib/assets/font/FiraSans-Regular.ttf
  assets:
    - lib/assets/images/adv_bg1.png
    - lib/assets/images/adv_bg2.png
    - lib/assets/images/adv_bg3.png
    - lib/assets/images/adv_bg4.png
    - lib/assets/images/adv_bg5.png
    - lib/assets/images/igor_logo.png
    - lib/assets/images/login_bg.png
    